### ISSUE TITLE
aws-amplify-react unused

### ISSUE THREAD

**Issue by krsnaa** [aws-samples/aws-amplify-auth-starters#1]
Why import aws-amplify-react if you are not going to use it anywhere?

This sample should be updated to also take advantage of aws-amplify-react and the withAuthenticator HOC since that is the path that the vast majority of users will tread with AWS-Amplify Auth.

A section on Social SignIn is also badly needed especially around integrating with IdPs like Twitter that are not natively supported on the Amplify / Cognito dashboard.

**Comment by Lucas-Geitner** [comment]
Fully agree with the need for Cognito and Twitter coupled, I have been looking for an example for some time.

**Comment by dabit3** [comment]
This example is meant to show how to create a custom authentication flow from scratch. I agree that the `withAuthenticator` is the simplest solution, but some people are interested in building their own custom solution.

**Comment by dabit3** [comment]
@krsnaa thanks for the feedback around Social Authentication, we will add this to our backlog of docs improvements.
