### ISSUE TITLE
Must run amplify init before react-native run-android

### ISSUE THREAD

**Issue by askpatrickw** [aws-samples/aws-amplify-auth-starters#10]
When you run `npx react-native run-android` and you've _never_ run amplify init before you will get a lot of missing file errors related to AWS (I didn't capture the log sorry). Once you do run init though you can run the android build and it will launch in the virtual Android device.

I think the README  just needs a tweak so you run `amplify init` before you run the build.
You CAN run the build before you push, you'll get a different error but you can see the app launch which is great for beginners. You should probably recommend running push first though as well.

I have new laptop and I think this is why I hit this;  if you've run amplify init before I don't think you will.

**Comment by dabit3** [comment]
Hey, thanks I'll make this update now!
