### ISSUE TITLE
react: sign-up does not work out of the box

### ISSUE THREAD

**Issue by glb** [aws-samples/aws-amplify-auth-starters#11]
Walking through the README and then trying to create a user, the sign-up page gives an error:

```
Attributes did not conform to the schema: custom:favorite_flavor: Attribute does not exist in the schema
```

Commenting out the [relevant line](https://github.com/aws-samples/aws-amplify-auth-starters/blob/fcc73785715dc6d3ae0710674b0dcc710ecd38fd/src/SignUp.js#L28) makes the error go away, but it makes me wonder if the intent was to have the schema include a custom attribute?

**Comment by Robbie-Cook** [comment]
I also had this problem. Could we get a fix guys?

**Comment by dabit3** [comment]
Thanks for the issue! Fix has been pushed.

**Comment by Robbie-Cook** [comment]
Thanks @dabit3
