### ISSUE TITLE
Can't read console.log in react native version

### ISSUE THREAD

**Issue by vincentk42** [aws-samples/aws-amplify-auth-starters#8]
I managed to get this running on my local emulator.  However, I am not able to read any type of console.logs.  When I start the bundler the app will load just fine, but then I get this message

> ::ffff:127.0.0.1 - - [15/Jan/2020:08:25:15 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 200 - "-" "okhttp/3.11.0"
> ::ffff:127.0.0.1 - - [15/Jan/2020:08:25:16 +0000] "GET /assets/src/assets/amplify.png?platform=android&hash=ea2db77f232a3a0a8fd05daf95808cdc HTTP/1.1" 200 - "-" "okhttp/3.11.0"

When I reload, I get 
 

> DELTA  [android, dev] ..\..\../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::ffff:127.0.0.1 - - [15/Jan/2020:08:28:05 +0000] "GET /index.delta?platform=android&dev=true&minify=false&deltaBundleId=501f65faf0ae5cbc HTTP/1.1" 200 69 "-" "okhttp/3.11.0"
>  DELTA  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

Everything else seems to work just fine.  Any ideas on why I'm not seeing any console.logs?

**Comment by dabit3** [comment]
Hey, just updated to the newest version of RN. Do you mind testing to see if this problem still exists? Thank you.
